# Generated by Django 5.0.1 on 2024-01-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('left_description', models.CharField(max_length=2040)),
                ('right_description', models.CharField(max_length=2040)),
                ('h_image_right', models.ImageField(upload_to='images/news/')),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
    ]
