# Generated by Django 5.0.1 on 2024-01-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/gallery/image')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImageSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_slide', models.ImageField(upload_to='images/gallery/slide')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryVideoSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_slide', models.FileField(upload_to='video/gallery/slide')),
            ],
        ),
    ]
