# Generated by Django 5.0.1 on 2024-01-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontentmodel_homefootermodel_homeheadermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homefootermodel',
            old_name='logo_header',
            new_name='logo_footer',
        ),
    ]
