# Generated by Django 5.0.1 on 2024-01-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teamcontentmodel_teampersonmodel_teamvaluesmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcontentmodel',
            old_name='team_description',
            new_name='mission_description',
        ),
    ]
