# Generated by Django 5.0.1 on 2024-01-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_teamcategorymembermodel_teamcategorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='teamcategorymembermodel',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_category', to='home.teamcategorymodel'),
        ),
        migrations.CreateModel(
            name='PaperCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_paper', to='home.paperdatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PaperPdfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdf/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_paper', to='home.papercategorymodel')),
            ],
        ),
    ]
