# Generated by Django 5.0.1 on 2024-01-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_papercategorymodel_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='papercategorymodel',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date_paper', to='home.paperdatemodel'),
            preserve_default=False,
        ),
    ]
