# Generated by Django 5.0.1 on 2024-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_teamcategorymodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcategorymodel',
            name='priority',
            field=models.IntegerField(max_length=100),
        ),
    ]
