# Generated by Django 5.0.1 on 2024-02-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_paperpdfmodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='paperpdfmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_category', to='home.papercategorymodel'),
        ),
        migrations.DeleteModel(
            name='PaperPdfTitleModel',
        ),
    ]
